### ISSUE TITLE
Create test project and add tests for IntervalCollection

### ISSUE THREAD

**Issue by konrad-kruczynski** [konrad-kruczynski/CovrIn#1]

**Comment by konrad-kruczynski** [comment]
Would you like do this? The test project should be general (for the library), but the first tests should be done for the IntervalCollection. Regarding the API, ask for anything you need. Of course add yourself as an author in README.

**Comment by PiotrZierhoffer** [comment]
As for now there is not much to test, please verify.

**Comment by konrad-kruczynski** [comment]
Approved.
