### ISSUE TITLE
Employ FluentIL or find alternative for tests

### ISSUE THREAD

**Issue by PiotrZierhoffer** [konrad-kruczynski/CovrIn#4]

**Comment by konrad-kruczynski** [comment]
I still wonder whether standard Cecil API (which is like Reflection.Emit API) is not sufficient.

**Comment by PiotrZierhoffer** [comment]
If we stick to the idea that we want to generate IL from source and then paste it to the tests, then either we use resources or we emit it in any way, FluentIl API will be generally not that important. Using Cecil API will reduce the amount of references, which is good.

I'd favour the second option. Having your code "in place" would help navigating and validating tests.

**Comment by PiotrZierhoffer** [comment]
So we stay with Cecil. Maybe we'll add helpers to reduce "Instruction.Create" length
