### ISSUE TITLE
IntervalCollection::Insert: prevent overlapping

### ISSUE THREAD

**Issue by konrad-kruczynski** [konrad-kruczynski/CovrIn#6]
Just throw an internal error (e.g. IOE exception) in such case.

**Comment by PiotrZierhoffer** [comment]
I'd go with ArgumentException, as this it the classical case.

**Comment by konrad-kruczynski** [comment]
But the method is private.

**Comment by konrad-kruczynski** [comment]
Short-sighted: actually there's a public as well. Then yeah, it's fine.

**Comment by PiotrZierhoffer** [comment]
Done
