### ISSUE TITLE
Decide what to do with jumps to next instruction

### ISSUE THREAD

**Issue by PiotrZierhoffer** [konrad-kruczynski/CovrIn#7]
Should we leave it as one block?

I believe it's not that important at the moment. After all, it's only one additional block.

**Comment by PiotrZierhoffer** [comment]
This is related to #3

**Comment by konrad-kruczynski** [comment]
Maybe that important but at the same time quite easy to fix. So I would glue two blocks.

**Comment by konrad-kruczynski** [comment]
I've committed proposed fix but left the test for you since you already deal with that.
